---
- name: create docker image and push to dockerhub
  hosts: all
  become: yes
  tasks:
    - name: install docker 
      apt:
        name: docker.io
        state: present

    - name: start docker
      service:
        name: docker
        state: started
...
